openapi: 3.0.0
info:
  title: CreditCalculation
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  '/v1/credits/{id-client}/schedule':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  field1:
                    type: integer
                    format: int64
      operationId: getScheduleByIdClient
      description: Получение списка платежей по id клиента
    parameters:
      - schema:
          type: string
        name: id-client
        in: path
        required: true
  /v1/credits/schedule:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  field1:
                    type: string
                  field2:
                    type: integer
                  filed3:
                    type: string
                    format: date-time
      operationId: getSchedule
      description: Получение списка платежей по параметрам
      parameters:
        - schema:
            type: string
          in: query
          name: id-product
        - schema:
            type: string
          in: query
          name: id-schedule
    parameters: []
    post:
      summary: ''
      operationId: createSchedule
      responses:
        '201':
          description: Created
      description: Создание списка платежей
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditDTO'
components:
  schemas:
    CreditDTO:
      title: CreditDTO
      type: object
      properties:
        loanAmount:
          type: number
          format: double
          default: 0
          minimum: 0
        interestRate:
          type: number
          format: double
          default: 0
          minimum: 0
        loanTermInMonths:
          type: number
          format: double
          default: 0
          minimum: 0
        dateReceiptLoan:
          type: string
          format: date
  responses: {}
